export const escrowStates = ["AWAITING_PAYMENT", "SECURED", "LOADING_PROOF_PENDING", "FIRST_RELEASE_PENDING", "FIRST_RELEASED", "DELIVERY_PROOF_PENDING", "SECOND_RELEASE_PENDING", "SECOND_RELEASED", "COMPLETED", "HELD_FOR_DISPUTE", "REFUNDED"] as const;
export type EscrowState = (typeof escrowStates)[number];
