"use client";
import { Download, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { formatINR } from "@/lib/format/currency";

const rows = [
  ["Produce value", 20000000], ["FPO operational share · 4%", 800000], ["AgriBridge share · 1%", 200000],
  ["Seller-borne assaying", -150000], ["Farmer payout", 18850000], ["Loading release · 50%", 9425000], ["Delivery release · balance", 9425000],
] as const;
export function MoneyBreakdown(){function read(){if("speechSynthesis" in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance("Produce value two lakh rupees. F P O share eight thousand. AgriBridge share two thousand. Assaying one thousand five hundred. Farmer payout one lakh eighty eight thousand five hundred. Two releases of ninety four thousand two hundred fifty."));}}function download(){const content=["AgriBridge settlement statement","Order AB-260914-1072",...rows.map(([l,v])=>`${l}: ${formatINR(v)}`)].join("\n");const blob=new Blob([content],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="agribridge-settlement-AB-260914-1072.txt";a.click();URL.revokeObjectURL(a.href);}return <Card className="overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-[var(--border)] p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-black tracking-[.14em] text-[var(--field)] uppercase">Distribution ledger</p><h2 className="mt-1 text-xl font-black">How the order amount is distributed</h2></div><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={read}><Volume2 size={17}/>Listen</Button><Button variant="secondary" size="sm" onClick={download}><Download size={17}/>Statement</Button></div></div><div className="divide-y divide-[var(--border)]">{rows.map(([label,value],index)=><div key={`${label}-${index}`} className={`flex justify-between gap-5 px-5 py-3 text-sm ${label==="Farmer payout"?"bg-[var(--surface-muted)] font-black":""}`}><span>{label}</span><span className="tabular whitespace-nowrap font-bold">{value<0?"− ":""}{formatINR(Math.abs(value))}</span></div>)}</div><div className="bg-[var(--forest)] p-5 text-sm text-white"><strong>Formula:</strong> 95% farmer pool − seller-borne charges. The odd paise, if any, stays in the second release so both releases exactly match the payout.</div></Card>}
