import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, Languages, Radio, ShieldCheck, Sprout, Truck } from "lucide-react";
import { CropVisual } from "@/components/features/crop-visual";
import { PageMotion } from "@/components/shared/page-motion";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { lots } from "@/lib/demo-data";
import { requireLocale } from "@/lib/i18n/locale";
import { LanguageSwitcher } from "@/components/shell/language-switcher";
import { InstallPrompt } from "@/components/shared/install-prompt";
import { getMessages } from "@/lib/i18n/request";
import { BrandLogo } from "@/components/shared/brand-logo";

export default async function LandingPage({ params }: { params: Promise<{ locale: string }> }) {
  const locale = requireLocale((await params).locale);
  const messages=await getMessages(locale);
  const hi = locale === "hi";
  return <PageMotion><main id="main-content" className="min-h-dvh">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 md:px-8"><Link href={`/${locale}`} aria-label="AgriBridge home" className="flex min-h-12 items-center"><BrandLogo className="max-w-[13rem]" /></Link><div className="flex items-center gap-2"><InstallPrompt/><LanguageSwitcher locale={locale} /><Link href={`/${locale}/login`} className={buttonVariants({ variant: "secondary" })}>{messages.auth.signIn}</Link></div></nav>
    <section className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-12 md:min-h-[72vh] md:grid-cols-[1.08fr_.92fr] md:px-8 md:py-20"><div><Badge className="mb-5"><BadgeCheck aria-hidden size={15} />{messages.nav.stock} · {messages.nav.marketplace} · {messages.nav.logistics}</Badge><h1 className="max-w-3xl text-5xl leading-[.98] font-black tracking-[-.055em] text-[var(--forest-deep)] md:text-7xl">{hi?"फसल को सही खरीदार और साफ़ हिसाब मिलता है।":locale==="en"?"Good harvests deserve clear deals.":messages.brand.tagline}</h1><p className="mt-6 max-w-xl text-lg text-[var(--text-muted)] md:text-xl">{hi ? "एफपीओ के सत्यापित स्टॉक, गुणवत्ता प्रमाण, परिवहन और चरणबद्ध भुगतान—एक सरल मंच पर।" : "Verified produce, quality evidence, logistics and milestone-based payouts—one practical workspace for FPOs and bulk buyers."}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={`/${locale}/demo-role`} className={buttonVariants({ variant: "harvest", size: "lg" })}>{messages.auth.demo}<ArrowRight aria-hidden size={19} /></Link><Link href={`/${locale}/buyer/marketplace`} className={buttonVariants({ variant: "secondary", size: "lg" })}>{messages.nav.marketplace}</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-[var(--text-muted)]"><span className="flex items-center gap-2"><ShieldCheck aria-hidden size={18} className="text-[var(--field)]" />Verified lot evidence</span><span className="flex items-center gap-2"><Languages aria-hidden size={18} className="text-[var(--field)]" />10 Indian languages</span><span className="flex items-center gap-2"><Radio aria-hidden size={18} className="text-[var(--field)]" />Works in mock mode</span></div></div>
      <div className="relative"><div className="absolute -top-5 -left-5 hidden h-full w-full rounded-[2rem] border-2 border-[var(--harvest)] md:block" /><Card className="relative overflow-hidden rounded-[2rem] border-0 bg-[var(--forest)] text-white shadow-[var(--shadow-md)]"><CropVisual code="POTATO · GONDA / LOT 018" colour="#E1B84B" alt="AI-generated demo photograph of the featured Grade A potato lot" priority showDemoLabel={false} /><div className="grid gap-5 p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-white/65">Today’s verified lot</p><h2 className="mt-1 text-2xl font-black">Grade A potato</h2></div><Badge className="border-white/20 bg-white/10 text-white">Lab verified</Badge></div><div className="grid grid-cols-3 gap-3 border-t border-white/15 pt-5"><div><p className="text-xs text-white/60">Available</p><p className="mt-1 font-black">42 t</p></div><div><p className="text-xs text-white/60">At FPO gate</p><p className="mt-1 font-black">₹18.50/kg</p></div><div><p className="text-xs text-white/60">AI confidence</p><p className="mt-1 font-black">94%</p></div></div></div></Card></div>
    </section>
    <section className="border-y border-[var(--border)] bg-white"><div className="mx-auto grid max-w-7xl gap-5 px-4 py-10 md:grid-cols-3 md:px-8">{[[Building2,"6","Active collection centres"],[Sprout,"18","Active produce lots"],[Truck,"3","Shipments moving today"]].map(([Icon,value,label]) => { const I = Icon as typeof Building2; return <div key={String(label)} className="flex items-center gap-4 p-3"><span className="grid size-12 place-items-center rounded-xl bg-[var(--surface-muted)] text-[var(--forest)]"><I aria-hidden /></span><div><p className="tabular text-2xl font-black">{String(value)}</p><p className="text-sm text-[var(--text-muted)]">{String(label)}</p></div></div>; })}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 md:px-8"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.16em] text-[var(--field)] uppercase">Fresh from verified collectives</p><h2 className="mt-2 text-3xl font-black tracking-tight">Trade-ready lots</h2></div><Link href={`/${locale}/buyer/marketplace`} className="hidden min-h-12 items-center gap-2 font-bold text-[var(--forest)] sm:flex">View marketplace <ArrowRight aria-hidden size={18} /></Link></div><div className="grid gap-5 md:grid-cols-3">{lots.slice(0,3).map((lot) => <Card key={lot.id} className="group overflow-hidden"><CropVisual code={lot.image} colour={lot.colour} compact alt={`AI-generated demo photograph of ${lot.variety} ${lot.name}`} showDemoLabel={false} /><div className="p-5"><div className="flex justify-between gap-4"><div><h3 className="text-lg font-black">{lot.name}</h3><p className="text-sm text-[var(--text-muted)]">{lot.variety} · {lot.location}</p></div><p className="tabular whitespace-nowrap font-black">₹{(lot.pricePaise/100).toFixed(2)}/kg</p></div></div></Card>)}</div><div className="mt-8 border-t border-[var(--border)] pt-6 text-sm text-[var(--text-muted)]">The stock photographs on this demo page are AI-generated and never represent a real lot. <Link className="inline-flex min-h-11 items-center font-bold text-[var(--forest)]" href={`/${locale}/credits`}>Review asset credits and licenses →</Link></div></section>
  </main></PageMotion>;
}
