import "server-only";
import {createCipheriv,createDecipheriv,randomBytes} from "node:crypto";
import {env} from "@/lib/config/env";

export type ProtectedValue={version:"v1";provider:"demo"|"local-aes"|"kms";keyId:string;ciphertext:string};
export interface FieldProtector{protect(value:string,context:string):Promise<ProtectedValue>;reveal(value:ProtectedValue,context:string):Promise<string>}
export class DemoReferenceProtector implements FieldProtector{async protect(value:string):Promise<ProtectedValue>{if(!/^(DEMO|MOCK|TEST)-/.test(value))throw new Error("Demo protection accepts synthetic references only");return{version:"v1",provider:"demo",keyId:"demo-not-encrypted",ciphertext:Buffer.from(value).toString("base64url")}}async reveal(value:ProtectedValue){if(value.provider!=="demo")throw new Error("Provider mismatch");return Buffer.from(value.ciphertext,"base64url").toString("utf8")}}
export class LocalAesGcmProtector implements FieldProtector{constructor(private readonly key:Buffer,private readonly keyId="local-development"){if(key.byteLength!==32)throw new Error("A 32-byte encryption key is required")}async protect(value:string,context:string):Promise<ProtectedValue>{const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",this.key,iv);cipher.setAAD(Buffer.from(context));const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);const tag=cipher.getAuthTag();return{version:"v1",provider:"local-aes",keyId:this.keyId,ciphertext:Buffer.concat([iv,tag,encrypted]).toString("base64url")}}async reveal(value:ProtectedValue,context:string){if(value.provider!=="local-aes")throw new Error("Provider mismatch");const payload=Buffer.from(value.ciphertext,"base64url");const decipher=createDecipheriv("aes-256-gcm",this.key,payload.subarray(0,12));decipher.setAAD(Buffer.from(context));decipher.setAuthTag(payload.subarray(12,28));return Buffer.concat([decipher.update(payload.subarray(28)),decipher.final()]).toString("utf8")}}
export class PendingKmsProtector implements FieldProtector{async protect():Promise<ProtectedValue>{throw new Error("KMS provider is not configured")};async reveal():Promise<string>{throw new Error("KMS provider is not configured")}}
export function createFieldProtector():FieldProtector{if(env.FIELD_ENCRYPTION_PROVIDER==="demo")return new DemoReferenceProtector();if(env.FIELD_ENCRYPTION_PROVIDER==="kms")return new PendingKmsProtector();if(!env.FIELD_ENCRYPTION_KEY_BASE64)throw new Error("FIELD_ENCRYPTION_KEY_BASE64 is required");return new LocalAesGcmProtector(Buffer.from(env.FIELD_ENCRYPTION_KEY_BASE64,"base64"))}
