"use server";
import { createHash,randomBytes } from "node:crypto";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { createAuthClient } from "@/lib/supabase/server";
import { getAccessContext } from "@/lib/authorization/access";
import { checkLocalRateLimit,privacyKey } from "@/lib/security/rate-limit";
import {configuredAuthOrigin} from "@/lib/auth/redirects";
import { isSupabaseAuthEnabled } from "@/lib/auth/auth-mode";
import { resolveAuthOnboardingEntry } from "@/lib/auth/resolve-signed-in-entry";
import type { AuthActionState } from "./action-state";

const organizationRoles=["fpo_admin","fpo_operator","fpo_finance","buyer_procurement","buyer_finance","logistics_dispatcher","logistics_driver"] as const;
export async function inviteMemberAction(_:AuthActionState,formData:FormData):Promise<AuthActionState>{const parsed=z.object({locale:z.string().regex(/^[a-z]{2}$/),organizationId:z.uuid(),organizationSlug:z.string(),email:z.email().transform((value)=>value.trim().toLowerCase()),roleKey:z.enum(organizationRoles)}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{status:"error",message:"Check the email and role."};const access=await getAccessContext(parsed.data.organizationSlug);if(!access?.organization||access.organization.id!==parsed.data.organizationId||!access.permissions.has("members.invite"))return{status:"error",message:"You do not have permission to invite members."};if(!checkLocalRateLimit("member-invite",privacyKey([access.user.id]),10,60*60_000).allowed)return{status:"error",message:"Invite limit reached. Try again later."};if(access.isDemo)return{status:"success",message:"Simulated invite recorded for the guided demo. No email was sent."};const allowedPrefix=access.organization.type==="fpo"?"fpo_":access.organization.type==="buyer"?"buyer_":"logistics_";if(!parsed.data.roleKey.startsWith(allowedPrefix))return{status:"error",message:"That role does not belong to this organization type."};const admin=createAdminClient();const{data:role}=await admin.from("roles").select("id").eq("key",parsed.data.roleKey).eq("scope","organization").maybeSingle();if(!role?.id)return{status:"error",message:"The selected role is unavailable."};const rawToken=randomBytes(32).toString("base64url");const tokenHash=createHash("sha256").update(rawToken).digest("hex");const expiresAt=new Date(Date.now()+7*24*60*60_000).toISOString();const{data:invite,error:insertError}=await admin.from("organization_invites").insert({organization_id:access.organization.id,email_normalized:parsed.data.email,role_id:role.id,token_hash:tokenHash,invited_by:access.user.id,expires_at:expiresAt}).select("id").single();if(insertError||!invite?.id)return{status:"error",message:"The invitation could not be created."};const redirectTo=`${configuredAuthOrigin()}/${parsed.data.locale}/invite/accept?token=${encodeURIComponent(rawToken)}`;const{error:mailError}=await admin.auth.admin.inviteUserByEmail(parsed.data.email,{redirectTo});if(mailError){await admin.from("organization_invites").delete().eq("id",invite.id);return{status:"error",message:"The invitation email could not be sent."};}await admin.from("auth_events").insert({user_id:access.user.id,organization_id:access.organization.id,event_type:"invite_sent",metadata:{invite_id:invite.id,role_key:parsed.data.roleKey}});return{status:"success",message:"Invitation sent. It expires in seven days and can be accepted once."};}

export async function acceptInviteAction(_:AuthActionState,formData:FormData):Promise<AuthActionState>{const parsed=z.object({locale:z.string().regex(/^[a-z]{2}$/),token:z.string().min(32).max(256)}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{status:"error",message:"This invitation is invalid or incomplete."};if(!isSupabaseAuthEnabled())return{status:"success",message:"Invitation acceptance is simulated in demo mode. No membership changed."};const client=(process.env.INTEGRATION_MODE??"mock")==="mock"?await createAuthClient():await createClient();const{data:{user}}=await client.auth.getUser();if(!user)redirect(`/${parsed.data.locale}/sign-in?next=${encodeURIComponent(`/${parsed.data.locale}/invite/accept?token=${parsed.data.token}`)}`);const{error}=await client.rpc("accept_organization_invitation",{invitation_token:parsed.data.token});if(error)return{status:"error",message:"This invitation is expired, used, revoked, or belongs to another email."};redirect((await resolveAuthOnboardingEntry(parsed.data.locale))??`/${parsed.data.locale}/organizations`);}
