"use client";
import { useState } from "react";
import Link from "next/link";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { formatINR } from "@/lib/format/currency";
const buyerRows=[["Produce value",20000000],["Buyer-borne freight",1820000],["Insurance",22000],["Applicable tax",0],["Disclosed provider charge",0]] as const;
export function CheckoutPanel({locale}:{locale:string}){const [paid,setPaid]=useState(false);const total=buyerRows.reduce((n,[,v])=>n+v,0);return <div className="grid gap-5 lg:grid-cols-[1fr_380px]"><div className="grid gap-5"><Card className="overflow-hidden"><div className="border-b border-[var(--border)] p-5"><p className="text-xs font-black tracking-[.14em] text-[var(--field)] uppercase">Buyer ledger</p><h2 className="mt-1 text-xl font-black">What the buyer pays</h2></div>{buyerRows.map(([label,value])=><div className="flex justify-between border-b border-[var(--border)] px-5 py-3 text-sm" key={label}><span>{label}</span><strong className="tabular">{formatINR(value)}</strong></div>)}<div className="flex justify-between bg-[var(--forest)] p-5 text-white"><strong>Total payable</strong><strong className="tabular text-xl">{formatINR(total)}</strong></div></Card><Card className="p-5"><h2 className="font-black">Selected logistics</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Medium goods vehicle · 7.5 t capacity · insured<br/>Pickup tomorrow 6 AM · delivery tomorrow 8 PM</p></Card></div><Card className="h-fit p-5"><ShieldCheck className="text-[var(--field)]"/><h2 className="mt-3 text-xl font-black">{paid?"Mock funds secured":"Secure the order"}</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{paid?"Provider webhook event recorded. This prototype does not move money or represent a regulated escrow arrangement.":"Choose mock UPI success to exercise the order flow. No real payment is collected."}</p>{!paid?<Button className="mt-6 w-full" onClick={()=>setPaid(true)}>Complete mock UPI payment</Button>:<div className="mt-6"><div className="mb-3 flex items-center gap-2 rounded-xl bg-[var(--surface-muted)] p-3 font-bold text-[var(--field)]"><CheckCircle2/>FUNDS SECURED</div><Link className={`${buttonVariants()} w-full`} href={`/${locale}/buyer/orders/AB-260914-1072`}>Open order</Link></div>}<p className="mt-4 text-xs text-[var(--text-muted)]">Milestone releases are controlled by validated server-side transitions, never a browser toggle.</p></Card></div>}
