"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { LayoutGrid, List, Search, ShieldCheck } from "lucide-react";
import { farmers } from "@/lib/demo-data";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/form-controls";
import { Button } from "@/components/ui/button";
import { StatusChip } from "@/components/shared/status-chip";
export function FarmerRegistry({ locale }: { locale: string }) { const [query,setQuery]=useState(""); const [grid,setGrid]=useState(false); const filtered=useMemo(()=>farmers.filter((f)=>`${f.name} ${f.village} ${f.crops}`.toLowerCase().includes(query.toLowerCase())),[query]); return <><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search farmers</span><Search className="absolute top-3.5 left-3 text-[var(--text-muted)]" aria-hidden size={20}/><Input className="pl-10" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search name, village or crop"/></label><div className="flex gap-2"><Button variant={!grid?"primary":"secondary"} size="icon" aria-label="List view" onClick={()=>setGrid(false)}><List aria-hidden/></Button><Button variant={grid?"primary":"secondary"} size="icon" aria-label="Grid view" onClick={()=>setGrid(true)}><LayoutGrid aria-hidden/></Button></div></div><div className={grid?"grid gap-4 md:grid-cols-2 xl:grid-cols-3":"grid gap-3"}>{filtered.map((farmer)=><Link key={farmer.id} href={`/${locale}/fpo/farmers/${farmer.id}`}><Card className={`min-h-24 p-4 transition hover:border-[var(--field)] hover:shadow-[var(--shadow-md)] ${grid?"":"grid items-center gap-3 sm:grid-cols-[1.5fr_1fr_1fr_auto]"}`}><div><div className="flex items-center gap-2"><h2 className="font-black">{farmer.name}</h2>{farmer.verified&&<ShieldCheck size={16} className="text-[var(--field)]" aria-label="Identity reference verified"/>}</div><p className="text-sm text-[var(--text-muted)]">{farmer.village}, Gonda</p></div><p className="mt-3 text-sm sm:mt-0"><span className="text-[var(--text-muted)]">Land</span><br/><strong>{farmer.land}</strong></p><p className="mt-3 text-sm sm:mt-0"><span className="text-[var(--text-muted)]">Crops</span><br/><strong>{farmer.crops}</strong></p><div className="mt-3 sm:mt-0"><StatusChip status={farmer.verified?"Verified":"Pending"}/></div></Card></Link>)}</div></>; }
