import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck, Box, CalendarDays, CheckCircle2, MapPin, Rotate3D, ShieldCheck } from "lucide-react";
import { CheckoutPanel } from "@/components/features/checkout-panel";
import { CropVisual } from "@/components/features/crop-visual";
import { GradingReport } from "@/components/features/grading-report";
import { LazySequenceViewer } from "@/components/features/lazy-sequence-viewer";
import { Marketplace } from "@/components/features/marketplace";
import { ProductActions } from "@/components/features/product-actions";
import { StatusChip } from "@/components/shared/status-chip";
import { PageHeader } from "@/components/shell/page-header";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { fpo, lots } from "@/lib/demo-data";
import { getCropAsset } from "@/lib/media/crop-assets";

export function MarketplaceContent({locale,basePath="/buyer"}:{locale:string;basePath?:string}){return <><PageHeader eyebrow="126 verified lots" title="Buyer marketplace" description="Compare trade-ready produce by location, grade, harvest date and certification."/><Marketplace locale={locale} basePath={basePath}/></>}

export function ProductContent({ locale, lotId, basePath = "/buyer" }: { locale: string; lotId: string; basePath?: string }) {
  const lot = lots.find((item) => item.id === lotId);
  if (!lot) notFound();
  const asset = getCropAsset(lot.image);
  return <><PageHeader eyebrow={`Verified lot · ${lot.id}`} title={lot.name} description={`${lot.variety} from ${lot.location}`} /><div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><Card className="overflow-hidden">{asset.sequenceKey ? <LazySequenceViewer crop={asset.sequenceKey} /> : <CropVisual code={lot.image} colour={lot.colour} alt={`AI-generated demo view of ${lot.variety} ${asset.label} offered by ${lot.fpo}`} priority />}<div className="flex items-center gap-3 p-5"><Rotate3D className="text-[var(--field)]" aria-hidden /><div><p className="font-black">{asset.sequenceKey ? "360° evidence viewer" : "Stock image · 360° capture pending"}</p><p className="text-sm text-[var(--text-muted)]">{asset.sequenceKey ? "12 guided demo angles · real deployments capture the listed lot at its FPO centre" : "AI-generated demo photograph only · a real lot must be captured and verified before publication"}</p></div></div></Card><div><div className="flex flex-wrap gap-2">{lot.certifications.map((certification) => <Badge key={certification}><BadgeCheck size={14} aria-hidden />{certification}</Badge>)}</div><p className="tabular mt-5 text-4xl font-black">₹{(lot.pricePaise / 100).toFixed(2)}<span className="text-lg font-medium text-[var(--text-muted)]"> / kg</span></p><div className="my-6 grid grid-cols-3 gap-3"><div className="rounded-xl bg-[var(--surface-muted)] p-3"><Box size={18} aria-hidden /><p className="mt-2 text-xs text-[var(--text-muted)]">Available</p><strong>{lot.quantityKg / 1000} t</strong></div><div className="rounded-xl bg-[var(--surface-muted)] p-3"><CalendarDays size={18} aria-hidden /><p className="mt-2 text-xs text-[var(--text-muted)]">Harvest</p><strong>{lot.harvest}</strong></div><div className="rounded-xl bg-[var(--surface-muted)] p-3"><MapPin size={18} aria-hidden /><p className="mt-2 text-xs text-[var(--text-muted)]">Pickup</p><strong>FPO gate</strong></div></div><Card className="mb-5 p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[var(--surface-muted)]"><ShieldCheck className="text-[var(--field)]" aria-hidden /></span><div><h2 className="font-black">{lot.fpo}</h2><p className="text-sm text-[var(--text-muted)]">{fpo.trustScore}% trust score · verified since {fpo.verifiedSince}</p></div></div></Card><ProductActions locale={locale} lotId={lot.id} basePath={basePath} /></div></div><div className="mt-6"><GradingReport /></div></>;
}

export function CompareContent({locale,basePath="/buyer"}:{locale:string;basePath?:string}){const chosen=lots.slice(0,3);return <><PageHeader eyebrow="Side-by-side evidence" title="Compare produce lots" description="Price, grade, quality evidence and pickup location in one decision view."/><Card className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr><th className="bg-[var(--surface-muted)] p-4">Attribute</th>{chosen.map(l=><th className="p-4" key={l.id}><span className="text-lg font-black">{l.name}</span><br/><span className="text-sm font-normal text-[var(--text-muted)]">{l.location}</span></th>)}</tr></thead><tbody>{[["Price",...chosen.map(l=>`₹${(l.pricePaise/100).toFixed(2)}/kg`)], ["Available",...chosen.map(l=>`${l.quantityKg/1000} t`)], ["Grade",...chosen.map(l=>`Grade ${l.grade}`)], ["AI confidence",...chosen.map(l=>`${l.confidence}%`)], ["Certification",...chosen.map(l=>l.certifications.join(", "))]].map(row=><tr className="border-t border-[var(--border)]" key={row[0]}>{row.map((cell,i)=><td className={`p-4 ${i===0?"bg-[var(--surface-muted)] font-bold":""}`} key={`${cell}-${i}`}>{i>0&&<CheckCircle2 className="mr-2 inline text-[var(--field)]" size={16}/>} {cell}</td>)}</tr>)}</tbody></table></Card><div className="mt-5 flex justify-end"><Link href={`/${locale}${basePath}/products/${chosen[0].id}`} className={buttonVariants()}>Inspect recommended lot</Link></div></>}

export function CheckoutContent({locale,orderId,basePath="/buyer"}:{locale:string;orderId:string;basePath?:string}){return <><PageHeader eyebrow={`Checkout · ${orderId}`} title="Review and secure order" description="10 t Grade A potato from Awadh Pragati FPC. Buyer and seller charges are shown separately."/><CheckoutPanel locale={locale} basePath={basePath}/></>}

export function BuyerOrdersContent({locale,basePath="/buyer"}:{locale:string;basePath?:string}){return <><PageHeader eyebrow="Purchase desk" title="Your orders" description="Track quality, logistics, provider payments and settlement milestones."/><div className="grid gap-4">{[["AB-260914-1072","Grade A potato · 10 t","Awadh Pragati FPC","₹2,18,420","IN_TRANSIT"],["AB-260831-0974","Red onion · 8 t","Sahyadri Growers Collective","₹2,31,200","COMPLETED"]].map(row=><Link key={row[0]} href={`/${locale}${basePath}/orders/${row[0]}`}><Card className="grid gap-3 p-5 transition hover:border-[var(--field)] md:grid-cols-[1fr_1.3fr_1.2fr_.8fr_auto] md:items-center"><strong className="text-[var(--forest)]">{row[0]}</strong><span>{row[1]}</span><span className="text-sm text-[var(--text-muted)]">{row[2]}</span><strong className="tabular">{row[3]}</strong><StatusChip status={row[4]}/></Card></Link>)}</div></>}
