import Link from "next/link";
import { Plus } from "lucide-react";
import { FarmerRegistry } from "@/components/features/farmer-registry";
import { CropVisual } from "@/components/features/crop-visual";
import { PageHeader } from "@/components/shell/page-header";
import { StatusChip } from "@/components/shared/status-chip";
import { buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { lots } from "@/lib/demo-data";

export function FarmersContent({locale,basePath="/fpo"}:{locale:string;basePath?:string}){return <><PageHeader eyebrow="1,248 farmer members" title="Farmer registry" description="Search verified member records, crop plans and payout history." actions={<Link href={`/${locale}${basePath}/farmers/new`} className={buttonVariants()}><Plus size={18}/>Register farmer</Link>}/><FarmerRegistry locale={locale} basePath={basePath}/></>}

export function StockContent({locale,basePath="/fpo"}:{locale:string;basePath?:string}){return <><PageHeader eyebrow="418 tonnes available" title="Stock management" description="Draft, published, reserved and sold produce from member farmers." actions={<Link href={`/${locale}${basePath}/stock/new`} className={buttonVariants()}><Plus size={18}/>Create stock lot</Link>}/><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{["All · 23","Draft · 5","Published · 18","Reserved · 4","Sold · 31","Expiring · 2"].map((x,i)=><button key={x} className={`min-h-11 shrink-0 rounded-xl px-4 text-sm font-bold ${i===0?"bg-[var(--forest)] text-white":"border border-[var(--border)] bg-white"}`}>{x}</button>)}</div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{lots.map(lot=><Link key={lot.id} href={`/${locale}${basePath}/stock/${lot.id}`}><Card className="overflow-hidden transition hover:-translate-y-1 hover:shadow-[var(--shadow-md)]"><CropVisual code={lot.image} colour={lot.colour} compact/><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">{lot.name}</h2><p className="text-sm text-[var(--text-muted)]">{lot.variety} · {lot.quantityKg/1000} t</p></div><StatusChip status="Published"/></div><div className="mt-4 flex justify-between border-t border-[var(--border)] pt-4 text-sm"><span>Grade <strong>{lot.grade}</strong></span><strong className="tabular">₹{(lot.pricePaise/100).toFixed(2)}/kg</strong></div></div></Card></Link>)}</div></>}

export function OrdersContent({locale,basePath="/fpo"}:{locale:string;basePath?:string}){const orders=[["AB-260914-1072","Lucknow Fresh Mart","Potato · 10 t","₹2,00,000","IN_TRANSIT"],["AB-260913-1068","NorthStar Exports","Basmati paddy · 25 t","₹9,62,500","FUNDS_SECURED"],["AB-260912-1059","Bharat Institutional Foods","Green peas · 6 t","₹2,64,000","LOADING"]];return <><PageHeader eyebrow="7 pending orders" title="FPO orders" description="Audited order states from placement through delivery."/><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[var(--surface-muted)] text-xs"><tr>{["Order","Buyer","Produce","Value","Status"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{orders.map(o=><tr className="border-t border-[var(--border)]" key={o[0]}><td className="p-4"><Link className="font-black text-[var(--forest)]" href={`/${locale}${basePath}/orders/${o[0]}`}>{o[0]}</Link></td><td className="p-4">{o[1]}</td><td className="p-4">{o[2]}</td><td className="tabular p-4 font-bold">{o[3]}</td><td className="p-4"><StatusChip status={o[4]}/></td></tr>)}</tbody></table></div></Card></>}
