import { stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { readManifest, root } from "./common";

const manifest = await readManifest();
const credits = ["# AgriBridge asset credits", "", "Generated files are synthetic demo artwork. Remote entries marked `needs-review` have not been downloaded or used.", ""];
for (const entry of manifest) credits.push(`- **${entry.slug}** — ${entry.attributionText}. [Source](${entry.sourcePageUrl}) · [${entry.licenseCode}](${entry.licenseUrl}) · status: ${entry.status}`);
await writeFile(path.join(root, "assets/attribution/CREDITS.md"), `${credits.join("\n")}\n`);

function stableUuid(value: string) {
  const hash = createHash("sha256").update(value).digest("hex");
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-a${hash.slice(17, 20)}-${hash.slice(20, 32)}`;
}
const sourceRows = manifest.map((entry) => ({ id: stableUuid(`source:${entry.slug}`), provider: entry.sourceProvider, source_page_url: entry.sourcePageUrl, source_asset_url: entry.downloadUrl, title: entry.altText.en, author: entry.author, license_code: entry.licenseCode, license_url: entry.licenseUrl, attribution_text: entry.attributionText, metadata: { status: entry.status, allowedUses: entry.allowedUses } }));
const generatedFiles = manifest.filter((entry) => entry.status === "generated").map(async (entry) => {
  const relative = new URL(entry.downloadUrl).pathname.replace("/generated/", "");
  const localPath = path.join(root, "assets/generated", relative);
  const info = await stat(localPath);
  const ext = path.extname(localPath);
  const mimeType = ext === ".svg" ? "image/svg+xml" : ext === ".pdf" ? "application/pdf" : "application/octet-stream";
  const bucket = relative.startsWith("brand/") || relative.startsWith("illustrations/") || relative.startsWith("vehicles/") ? "public-brand-assets" : relative.startsWith("documents/khatauni") ? "farmer-documents" : relative.startsWith("documents/grading") ? "grading-certificates" : relative.startsWith("documents/") ? "delivery-proofs" : "public-listing-media";
  return { id: stableUuid(`file:${entry.slug}`), source_id: stableUuid(`source:${entry.slug}`), bucket, object_path: `demo/${relative}`, original_filename: path.basename(relative), mime_type: mimeType, byte_size: info.size, checksum_sha256: entry.checksumSha256!, visibility: bucket.startsWith("public-") ? "public" : "private", purpose: entry.kind, processing_status: "ready", quarantine_status:"clean",scan_provider:"deterministic-local-generator",is_synthetic: true, alt_text: entry.altText, metadata: { seed: "agribridge-demo-v1" } };
});
const fileRows = await Promise.all(generatedFiles);
const lots=[
  ["50000000-0000-0000-0000-000000000001","10000000-0000-0000-0000-000000000001","potato"],
  ["50000000-0000-0000-0000-000000000002","10000000-0000-0000-0000-000000000001","onion"],
  ["50000000-0000-0000-0000-000000000003","10000000-0000-0000-0000-000000000001","tomato"],
  ["50000000-0000-0000-0000-000000000004","10000000-0000-0000-0000-000000000001","paddy"],
  ["50000000-0000-0000-0000-000000000005","10000000-0000-0000-0000-000000000001","peas"],
  ["50000000-0000-0000-0000-000000000006","10000000-0000-0000-0000-000000000001","mango"],
  ["50000000-0000-0000-0000-000000000007","10000000-0000-0000-0000-000000000002","onion"],
  ["50000000-0000-0000-0000-000000000008","10000000-0000-0000-0000-000000000002","tomato"],
] as const;
const associations=lots.flatMap(([lotId,organizationId,crop])=>{const coverSlug=`crops-${crop}-cover`;const cover={id:stableUuid(`binding:${lotId}:${coverSlug}`),organization_id:organizationId,stock_lot_id:lotId,file_asset_id:stableUuid(`file:${coverSlug}`),position:0,view_angle:null,is_cover:true};if(!["potato","tomato"].includes(crop))return[cover];return[cover,...Array.from({length:12},(_,index)=>{const slug=`360-${crop}-frame-${String(index+1).padStart(2,"0")}`;return{id:stableUuid(`binding:${lotId}:${slug}`),organization_id:organizationId,stock_lot_id:lotId,file_asset_id:stableUuid(`file:${slug}`),position:index+1,view_angle:index*30,is_cover:false}})]});
const sql = [`-- Generated by pnpm assets:seed. Safe, idempotent demo metadata only.`, `-- ${sourceRows.length} asset_sources and ${fileRows.length} file_assets are represented by the manifest.`, `-- Use configured Supabase credentials to perform JSON upserts; no secrets are written here.`].join("\n");
await writeFile(path.join(root, "assets/processed/seed-media.sql"), `${sql}\n`);

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) { console.log(`Generated credits and ${fileRows.length} stable media rows. Database upsert skipped: demo credentials are not configured.`); process.exit(0); }
const client = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
const { error: sourceError } = await client.from("asset_sources").upsert(sourceRows, { onConflict: "id" });
if (sourceError) throw sourceError;
const { error: fileError } = await client.from("file_assets").upsert(fileRows, { onConflict: "id" });
if (fileError) throw fileError;
const{error:associationError}=await client.from("stock_lot_assets").upsert(associations,{onConflict:"id"});if(associationError)throw associationError;
console.log(`Upserted ${sourceRows.length} sources, ${fileRows.length} files and ${associations.length} lot bindings without duplicates.`);
