"use client";
import Link from "next/link";
import { useActionState } from "react";
import {useTranslations} from "next-intl";
import { ArrowRight, CircleAlert, CircleCheck, Mail } from "lucide-react";
import { signInAction, signUpAction, forgotPasswordAction, resetPasswordAction, resendVerificationAction, initialAuthState } from "@/features/auth/actions";
import { Button } from "@/components/ui/button";
import { Field, Input, Select } from "@/components/ui/form-controls";
import { PasswordInput } from "./password-input";

function Result({ state }: { state: typeof initialAuthState }) { if (state.status === "idle") return null; const Icon=state.status==="success"?CircleCheck:CircleAlert; return <div role={state.status==="error"?"alert":"status"} className={`flex gap-3 rounded-xl border p-3 text-sm ${state.status==="success"?"border-green-200 bg-green-50 text-green-900":"border-red-200 bg-red-50 text-red-900"}`}><Icon className="mt-0.5 shrink-0" aria-hidden size={18}/><p>{state.message}</p></div>; }

export function SignInForm({ locale, next }: { locale: string; next?: string }) { const [state,action,pending]=useActionState(signInAction,initialAuthState);const t=useTranslations("auth"); return <form action={action} className="grid gap-5"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="next" value={next ?? ""}/><Field label={t("email")}><div className="relative"><Mail className="absolute top-3.5 left-3 text-[var(--text-muted)]" aria-hidden size={19}/><Input className="pl-10" name="email" type="email" autoComplete="email" required/></div></Field><Field label={t("password")}><PasswordInput name="password"/></Field><div className="-mt-2 text-right"><Link href={`/${locale}/forgot-password`} className="inline-flex min-h-11 items-center font-bold text-[var(--forest)]">Forgot password?</Link></div><Result state={state}/><Button disabled={pending}>{pending?"Signing in…":t("signIn")}<ArrowRight aria-hidden size={18}/></Button><p className="text-center text-sm text-[var(--text-muted)]">New to AgriBridge? <Link className="font-bold text-[var(--forest)]" href={`/${locale}/sign-up`}>Create an account</Link></p><Link href={`/${locale}/demo-role`} className="flex min-h-12 items-center justify-center rounded-xl border border-[var(--border)] bg-[var(--surface-muted)] px-4 font-bold text-[var(--forest)]">{t("demo")}</Link></form>; }

export function SignUpForm({ locale }: { locale: string }) { const [state,action,pending]=useActionState(signUpAction,initialAuthState); return <form action={action} className="grid gap-5"><input type="hidden" name="locale" value={locale}/><Field label="Account type" hint="This selects onboarding only; it does not grant a privileged role."><Select name="accountType" required defaultValue="fpo"><option value="fpo">Farmer Producer Organization</option><option value="buyer">Bulk buyer</option><option value="logistics">Logistics partner</option></Select></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Your name"><Input name="displayName" autoComplete="name" required/></Field><Field label="Organization name"><Input name="organizationName" autoComplete="organization" required/></Field></div><Field label="Work email"><Input name="email" type="email" autoComplete="email" required/></Field><Field label="Password" hint="At least 10 characters."><PasswordInput name="password" autoComplete="new-password" minLength={10}/></Field><label className="flex gap-3 text-sm"><input className="mt-1 size-5 shrink-0 accent-[var(--forest)]" type="checkbox" name="consent" required/><span>I agree to the prototype terms and consent notice. I will not enter real Aadhaar, bank, biometric, or payment credentials.</span></label><Result state={state}/><Button disabled={pending}>{pending?"Creating account…":"Create account"}<ArrowRight aria-hidden size={18}/></Button><p className="text-center text-sm">Already registered? <Link className="font-bold text-[var(--forest)]" href={`/${locale}/sign-in`}>Sign in</Link></p></form>; }

export function ForgotPasswordForm({ locale }: { locale:string }) { const [state,action,pending]=useActionState(forgotPasswordAction,initialAuthState); return <form action={action} className="grid gap-5"><input type="hidden" name="locale" value={locale}/><Field label="Email address"><Input name="email" type="email" autoComplete="email" required/></Field><Result state={state}/><Button disabled={pending}>{pending?"Sending…":"Send reset instructions"}</Button><Link className="flex min-h-11 items-center justify-center font-bold text-[var(--forest)]" href={`/${locale}/sign-in`}>Back to sign in</Link></form>; }

export function ResetPasswordForm({ locale }: { locale:string }) { const [state,action,pending]=useActionState(resetPasswordAction,initialAuthState); return <form action={action} className="grid gap-5"><input type="hidden" name="locale" value={locale}/><Field label="New password"><PasswordInput name="password" autoComplete="new-password" minLength={10}/></Field><Field label="Confirm password"><PasswordInput name="confirmation" autoComplete="new-password" minLength={10}/></Field><Result state={state}/><Button disabled={pending}>{pending?"Updating…":"Update password"}</Button></form>; }

export function ResendVerificationForm({ locale, email }: { locale:string; email?:string }) { const [state,action,pending]=useActionState(resendVerificationAction,initialAuthState); return <form action={action} className="grid gap-4"><input type="hidden" name="locale" value={locale}/><Field label="Email address"><Input name="email" type="email" autoComplete="email" defaultValue={email} required/></Field><Result state={state}/><Button variant="secondary" disabled={pending}>{pending?"Sending…":"Resend verification email"}</Button></form>; }
